// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using _2.Data.DbContexts;

#nullable disable

namespace _2.Data.Migrations
{
    [DbContext(typeof(DoAnNhanhDbContext))]
    [Migration("20230317175447_seeddata")]
    partial class seeddata
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("_2.Data.ModelsClass.Combo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AnhCombo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("GiaBan")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("IdDoUong")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdMonAn")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("IdDoUong");

                    b.HasIndex("IdMonAn");

                    b.ToTable("Combo", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("f433cbcc-5300-45ce-bd6c-c41dc87b3f30"),
                            GiaBan = 100000m,
                            IdDoUong = new Guid("a6640bfb-ee82-45f9-8111-0fffb4e06a6a"),
                            IdMonAn = new Guid("008e2497-081b-4e33-8781-5004edfdf479"),
                            SoLuong = 10,
                            Ten = "Combo Hạnh Phúc"
                        },
                        new
                        {
                            Id = new Guid("0b061962-0e18-469b-a59e-7435bae36ded"),
                            GiaBan = 200000m,
                            IdDoUong = new Guid("3cb233cb-a774-4c65-993e-f36af6ba178e"),
                            IdMonAn = new Guid("7e9fe1cf-11cf-4ff1-9bff-b5dea3803b82"),
                            SoLuong = 10,
                            Ten = "Combo Không Hạnh Phúc"
                        },
                        new
                        {
                            Id = new Guid("7cb5f225-8db2-4d48-9f73-68a42b78c1d2"),
                            GiaBan = 300000m,
                            IdDoUong = new Guid("68ba1ddf-46b0-4d88-987b-e1d0852ef1c7"),
                            IdMonAn = new Guid("e7dbf7d6-95d0-4294-b801-f63bc610a746"),
                            SoLuong = 10,
                            Ten = "Combo Rất Hạnh Phúc"
                        });
                });

            modelBuilder.Entity("_2.Data.ModelsClass.DoUong", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AnhDoUong")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("GiaBan")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("GiaNhap")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("DoUong", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("a6640bfb-ee82-45f9-8111-0fffb4e06a6a"),
                            GiaBan = 15000m,
                            GiaNhap = 12000m,
                            SoLuong = 10,
                            Ten = "Coca",
                            TrangThai = true
                        },
                        new
                        {
                            Id = new Guid("3cb233cb-a774-4c65-993e-f36af6ba178e"),
                            GiaBan = 12000m,
                            GiaNhap = 10000m,
                            SoLuong = 10,
                            Ten = "Pepsi",
                            TrangThai = true
                        },
                        new
                        {
                            Id = new Guid("68ba1ddf-46b0-4d88-987b-e1d0852ef1c7"),
                            GiaBan = 10000m,
                            GiaNhap = 7000m,
                            SoLuong = 10,
                            Ten = "Nước Lọc",
                            TrangThai = true
                        });
                });

            modelBuilder.Entity("_2.Data.ModelsClass.GioHang", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdKhachHang")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("IdKhachHang");

                    b.ToTable("GioHang", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("4f7b6227-fd02-407a-8191-604739739697"),
                            IdKhachHang = new Guid("9fd94a59-1ab2-4eae-9654-767481e96bfe")
                        });
                });

            modelBuilder.Entity("_2.Data.ModelsClass.GioHangChiTiet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("GiaBan")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid?>("IdCombo")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("IdDoUong")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("IdGioHang")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("IdMonAn")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdCombo");

                    b.HasIndex("IdDoUong");

                    b.HasIndex("IdGioHang");

                    b.HasIndex("IdMonAn");

                    b.ToTable("GioHangChiTiet", (string)null);
                });

            modelBuilder.Entity("_2.Data.ModelsClass.HoaDon", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DiaChi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("IdKhachHang")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdNhanVien")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("MaHoaDon")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("TongTien")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("IdKhachHang");

                    b.HasIndex("IdNhanVien");

                    b.ToTable("HoaDon", (string)null);
                });

            modelBuilder.Entity("_2.Data.ModelsClass.HoaDonChiTiet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("GiaBan")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid?>("IdComBo")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("IdDoUong")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("IdHoaDon")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("IdMonAn")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdComBo");

                    b.HasIndex("IdDoUong");

                    b.HasIndex("IdHoaDon");

                    b.HasIndex("IdMonAn");

                    b.ToTable("HoaDonChiTiet", (string)null);
                });

            modelBuilder.Entity("_2.Data.ModelsClass.KhachHang", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DiaChi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("GioiTinh")
                        .HasColumnType("bit");

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sdt")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("KhachHang", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("9fd94a59-1ab2-4eae-9654-767481e96bfe"),
                            DiaChi = "a",
                            Email = "tienncph18949@fpt.edu.vn",
                            GioiTinh = true,
                            MatKhau = "123456",
                            Sdt = "0987654321",
                            Ten = "A"
                        });
                });

            modelBuilder.Entity("_2.Data.ModelsClass.Loai", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Loai", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("bc387d89-bebe-4897-baf0-0ea4e7028a13"),
                            Ten = "Pizza",
                            TrangThai = true
                        },
                        new
                        {
                            Id = new Guid("22516479-1dfe-4780-b8e0-85c885882aff"),
                            Ten = "Xà lách",
                            TrangThai = true
                        });
                });

            modelBuilder.Entity("_2.Data.ModelsClass.MonAn", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AnhMonAn")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("GiaBan")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("GiaNhap")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("IdLoai")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("IdLoai");

                    b.ToTable("MonAn", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("008e2497-081b-4e33-8781-5004edfdf479"),
                            GiaBan = 100000m,
                            GiaNhap = 70000m,
                            IdLoai = new Guid("bc387d89-bebe-4897-baf0-0ea4e7028a13"),
                            SoLuong = 15,
                            Ten = "Pizza Bò",
                            TrangThai = true
                        },
                        new
                        {
                            Id = new Guid("7e9fe1cf-11cf-4ff1-9bff-b5dea3803b82"),
                            GiaBan = 100000m,
                            GiaNhap = 70000m,
                            IdLoai = new Guid("bc387d89-bebe-4897-baf0-0ea4e7028a13"),
                            SoLuong = 15,
                            Ten = "Pizza Lợn",
                            TrangThai = true
                        },
                        new
                        {
                            Id = new Guid("e7dbf7d6-95d0-4294-b801-f63bc610a746"),
                            GiaBan = 100000m,
                            GiaNhap = 70000m,
                            IdLoai = new Guid("bc387d89-bebe-4897-baf0-0ea4e7028a13"),
                            SoLuong = 15,
                            Ten = "Pizza Xúc Xích",
                            TrangThai = true
                        },
                        new
                        {
                            Id = new Guid("52c4a9d4-75ec-4d96-a046-bca3a3831b3a"),
                            GiaBan = 100000m,
                            GiaNhap = 70000m,
                            IdLoai = new Guid("22516479-1dfe-4780-b8e0-85c885882aff"),
                            SoLuong = 15,
                            Ten = "Xà lách trộn bò",
                            TrangThai = true
                        },
                        new
                        {
                            Id = new Guid("11d8d7f4-318e-4209-9605-04b1260e008c"),
                            GiaBan = 100000m,
                            GiaNhap = 70000m,
                            IdLoai = new Guid("22516479-1dfe-4780-b8e0-85c885882aff"),
                            SoLuong = 15,
                            Ten = "Xà lách trộn lợn",
                            TrangThai = true
                        },
                        new
                        {
                            Id = new Guid("d6776c14-9f11-4a94-a525-e826d96c6c2e"),
                            GiaBan = 100000m,
                            GiaNhap = 70000m,
                            IdLoai = new Guid("22516479-1dfe-4780-b8e0-85c885882aff"),
                            SoLuong = 15,
                            Ten = "Xà lách trộn xúc xích",
                            TrangThai = true
                        });
                });

            modelBuilder.Entity("_2.Data.ModelsClass.NhanVien", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DiaChi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("GioiTinh")
                        .HasColumnType("bit");

                    b.Property<Guid?>("IdGuiBaoCao")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("IdGuiBcNavigationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sdt")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("IdGuiBcNavigationId");

                    b.ToTable("NhanVien", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("b54e5b6d-2309-4844-99f6-50b18f665440"),
                            DiaChi = "hd",
                            Email = "hdgnguyentien@gmail.com",
                            GioiTinh = true,
                            MatKhau = "123456",
                            Sdt = "0987654322",
                            Ten = "tien"
                        });
                });

            modelBuilder.Entity("_2.Data.ModelsClass.Combo", b =>
                {
                    b.HasOne("_2.Data.ModelsClass.DoUong", "doUong")
                        .WithMany("combos")
                        .HasForeignKey("IdDoUong")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("_2.Data.ModelsClass.MonAn", "monAn")
                        .WithMany("combos")
                        .HasForeignKey("IdMonAn")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("doUong");

                    b.Navigation("monAn");
                });

            modelBuilder.Entity("_2.Data.ModelsClass.GioHang", b =>
                {
                    b.HasOne("_2.Data.ModelsClass.KhachHang", "khachHang")
                        .WithMany("gioHangs")
                        .HasForeignKey("IdKhachHang")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("khachHang");
                });

            modelBuilder.Entity("_2.Data.ModelsClass.GioHangChiTiet", b =>
                {
                    b.HasOne("_2.Data.ModelsClass.Combo", "combo")
                        .WithMany("gioHangChiTiets")
                        .HasForeignKey("IdCombo");

                    b.HasOne("_2.Data.ModelsClass.DoUong", "doUong")
                        .WithMany("gioHangChiTiets")
                        .HasForeignKey("IdDoUong");

                    b.HasOne("_2.Data.ModelsClass.GioHang", "gioHang")
                        .WithMany("gioHangChiTiets")
                        .HasForeignKey("IdGioHang");

                    b.HasOne("_2.Data.ModelsClass.MonAn", "monAn")
                        .WithMany("gioHangChiTiets")
                        .HasForeignKey("IdMonAn");

                    b.Navigation("combo");

                    b.Navigation("doUong");

                    b.Navigation("gioHang");

                    b.Navigation("monAn");
                });

            modelBuilder.Entity("_2.Data.ModelsClass.HoaDon", b =>
                {
                    b.HasOne("_2.Data.ModelsClass.KhachHang", "khachHang")
                        .WithMany("hoaDons")
                        .HasForeignKey("IdKhachHang")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("_2.Data.ModelsClass.NhanVien", "nhanVien")
                        .WithMany("hoaDons")
                        .HasForeignKey("IdNhanVien")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("khachHang");

                    b.Navigation("nhanVien");
                });

            modelBuilder.Entity("_2.Data.ModelsClass.HoaDonChiTiet", b =>
                {
                    b.HasOne("_2.Data.ModelsClass.Combo", "combo")
                        .WithMany("hoaDonChiTiets")
                        .HasForeignKey("IdComBo");

                    b.HasOne("_2.Data.ModelsClass.DoUong", "doUong")
                        .WithMany("hoaDonChiTiets")
                        .HasForeignKey("IdDoUong");

                    b.HasOne("_2.Data.ModelsClass.HoaDon", "hoaDon")
                        .WithMany("hoaDonChiTiets")
                        .HasForeignKey("IdHoaDon");

                    b.HasOne("_2.Data.ModelsClass.MonAn", "monAn")
                        .WithMany("hoaDonChiTiets")
                        .HasForeignKey("IdMonAn");

                    b.Navigation("combo");

                    b.Navigation("doUong");

                    b.Navigation("hoaDon");

                    b.Navigation("monAn");
                });

            modelBuilder.Entity("_2.Data.ModelsClass.MonAn", b =>
                {
                    b.HasOne("_2.Data.ModelsClass.Loai", "loai")
                        .WithMany("monAns")
                        .HasForeignKey("IdLoai")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("loai");
                });

            modelBuilder.Entity("_2.Data.ModelsClass.NhanVien", b =>
                {
                    b.HasOne("_2.Data.ModelsClass.NhanVien", "IdGuiBcNavigation")
                        .WithMany("InverseIdGuiBcNavigation")
                        .HasForeignKey("IdGuiBcNavigationId");

                    b.Navigation("IdGuiBcNavigation");
                });

            modelBuilder.Entity("_2.Data.ModelsClass.Combo", b =>
                {
                    b.Navigation("gioHangChiTiets");

                    b.Navigation("hoaDonChiTiets");
                });

            modelBuilder.Entity("_2.Data.ModelsClass.DoUong", b =>
                {
                    b.Navigation("combos");

                    b.Navigation("gioHangChiTiets");

                    b.Navigation("hoaDonChiTiets");
                });

            modelBuilder.Entity("_2.Data.ModelsClass.GioHang", b =>
                {
                    b.Navigation("gioHangChiTiets");
                });

            modelBuilder.Entity("_2.Data.ModelsClass.HoaDon", b =>
                {
                    b.Navigation("hoaDonChiTiets");
                });

            modelBuilder.Entity("_2.Data.ModelsClass.KhachHang", b =>
                {
                    b.Navigation("gioHangs");

                    b.Navigation("hoaDons");
                });

            modelBuilder.Entity("_2.Data.ModelsClass.Loai", b =>
                {
                    b.Navigation("monAns");
                });

            modelBuilder.Entity("_2.Data.ModelsClass.MonAn", b =>
                {
                    b.Navigation("combos");

                    b.Navigation("gioHangChiTiets");

                    b.Navigation("hoaDonChiTiets");
                });

            modelBuilder.Entity("_2.Data.ModelsClass.NhanVien", b =>
                {
                    b.Navigation("InverseIdGuiBcNavigation");

                    b.Navigation("hoaDons");
                });
#pragma warning restore 612, 618
        }
    }
}
